name: CD (Canary)

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      BuildTitle:
        description: Build Title
        required: false

jobs:
  distribute:
    runs-on: [self-hosted, android]

    steps:
      - name: Runner Info

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribute: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Android Build
        run: |
          if [[ github.event.inputs.BuildTitle == '' ]]
            echo empty
          else
            echo not empty
          fi