name: CD (Canary)

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      BuildTitle:
        description: Build Title
        required: false
        type: string

jobs:
  distribute:
    runs-on: [self-hosted]

    steps:
      - name: Runner Info
        run: |
          echo "$(whoami)@$(scutil --get ComputerName)"
          echo "OS Version: $(sw_vers -productVersion)"
          echo "Ruby(rbenv): $(rbenv global)"
          echo "Ruby: $(ruby --version)"

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Android Build
        run: |
          if [ '${{ github.event.inputs.BuildTitle }}' == '' ]
          then
            echo "empty"
          else
            echo "not empty"
          fi